version "3.3.2"

#include "zscript/DevilMazePlayer/DevilMazePlayer.zc"
#include "zscript/DevilMazeHUD/DevilMazeHUD.zc"
#include "zscript/DevilMazeDecorations/DevilMazeSkull.zc"
#include "zscript/DevilMazeMonsters/DevilMazeMonster.zc"
#include "zscript/DevilMazeInventory/DevilMazeKey.zc"
#include "zscript/DevilMazeDecorations/DevilMazeCandle.zc"
#include "zscript/DevilMazeDecorations/DevilMazeCorpse.zc"
